name: flutter_unit
description: A new Flutter application.

version: 1.5.2
author: 张风捷特烈 <1981462002@qq.com>
homepage: https://juejin.cn/user/149189281194766/posts

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  equatable: ^2.0.3
  flutter_bloc: ^7.0.1
  flutter_markdown: ^0.6.2
  flutter_spinkit: ^5.0.0
  flutter_star: ^1.0.2
  intl: ^0.17.0
  jwt_decoder: ^2.0.1
  path_provider: ^2.0.2
  share: ^2.0.4
  shared_preferences: ^2.0.6
  sqflite: ^2.0.0+3
  toggle_rotate: ^1.0.1
  url_launcher: ^6.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/head_icon/
    - assets/images/widgets/
    - assets/flutter.db
    - assets/version.json

  fonts: # 配置字体，可配置多个，支持ttf和otf,ttc等字体资源
    - family: IndieFlower #字体名
      fonts:
        - asset: assets/fonts/IndieFlower-Regular.ttf
    - family: BalooBhai2 #字体名
      fonts:
        - asset: assets/fonts/BalooBhai2-Regular.ttf
    - family: Inconsolata #字体名
      fonts:
        - asset: assets/fonts/Inconsolata-Regular.ttf
    - family: Neucha #字体名
      fonts:
        - asset: assets/fonts/Neucha-Regular.ttf
    - family: ComicNeue #字体名
      fonts:
        - asset: assets/fonts/ComicNeue-Regular.ttf
    - family: CHOPS
      fonts:
        - asset: assets/fonts/CHOPS.TTF
    - family: TolyIcon
      fonts:
        - asset: assets/iconfont/iconfont.ttf
